title: Muyang Li
email: ml2855@cornell.edu
description: >- 
  M.Eng. ECE @ Cornell | Backend, Fullstack, Database
baseurl: ""
url: "https://muyangli2855.github.io"
linkedin_username: ml2855
github_username: muyangli2855
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
paginate: 0
show_excerpts: false
rss: false
header_pages:
  - projects.md